"""Shared FastAPI dependencies — get_db, get_redis, get_current_user."""

from collections.abc import AsyncGenerator
from typing import Annotated
from uuid import UUID

from fastapi import Depends, Header, HTTPException, Request, status
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer
from redis.asyncio import Redis
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import AsyncSessionLocal, set_session_org_id
from app.models.api_key import ApiKey
from app.models.user import User
from app.services.auth_service import validate_api_key, verify_access_token
from app.utils.logging import request_id_ctx

http_bearer = HTTPBearer(auto_error=False)

async def get_db() -> AsyncGenerator[AsyncSession, None]:
    """Yield an async DB session, auto-close after request."""
    async with AsyncSessionLocal() as session:
        yield session


async def get_redis(request: Request) -> Redis:
    """Return the app-level Redis connection pool."""
    return request.app.state.redis


async def get_current_user_from_jwt(
    credentials: HTTPAuthorizationCredentials | None = Depends(http_bearer),
    db: AsyncSession = Depends(get_db),
    redis: Redis = Depends(get_redis),
) -> User:
    """Authenticate a management API request using bearer JWT."""
    if credentials is None or not credentials.credentials:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Missing token")

    token = credentials.credentials
    payload = await verify_access_token(token, redis=redis)

    sub = payload.get("sub")
    org_id_raw = payload.get("org_id")
    if not sub or not org_id_raw:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid token")

    try:
        org_uuid = UUID(str(org_id_raw))
        sub_uuid = UUID(str(sub))
    except (ValueError, TypeError):
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid token")

    await set_session_org_id(db, org_uuid)
    user = await db.scalar(select(User).where(User.id == sub_uuid, User.org_id == org_uuid))
    if user is None or not user.is_active:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid credentials")
    return user


async def get_current_user_from_api_key(
    authorization: str | None = Header(default=None, alias="Authorization"),
    db: AsyncSession = Depends(get_db),
    redis: Redis = Depends(get_redis),
) -> tuple[User, ApiKey]:
    """Authenticate proxy request using bearer API key format."""
    if not authorization:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Missing token")

    parts = authorization.split(" ", maxsplit=1)
    if len(parts) != 2 or parts[0].lower() != "bearer":
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid credentials")

    credential = parts[1].strip()
    if not credential.startswith("opai_"):
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid credentials")

    key_model = await validate_api_key(db=db, redis=redis, api_key=credential)
    if key_model.user is None:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid credentials")
    return key_model.user, key_model


CurrentUser = Annotated[User, Depends(get_current_user_from_jwt)]
ProxyAuth = Annotated[tuple[User, ApiKey], Depends(get_current_user_from_api_key)]


async def get_request_id() -> str:
    """Expose request id generated by middleware for route-level dependencies."""
    return request_id_ctx.get()


def get_real_ip(request: Request) -> str:
    forwarded_for = request.headers.get("X-Forwarded-For")
    if forwarded_for:
        return forwarded_for.split(",")[0].strip()
    return request.client.host if request.client else "unknown"
