{{- if and .Values.prometheus.serviceMonitor.enabled (or (not (hasKey .Values.prometheus.serviceMonitor "create")) .Values.prometheus.serviceMonitor.create) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "openproxy.fullname" . }}
  labels:
    {{- include "openproxy.labels" . | nindent 4 }}
    {{- with .Values.prometheus.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "openproxy.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.prometheus.serviceMonitor.interval | default "30s" }}
      scrapeTimeout: {{ .Values.prometheus.serviceMonitor.scrapeTimeout | default "10s" }}
{{- end }}
